### ISSUE TITLE
capturePoints.clusters as opposed to multiple cluster lists

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#100]
Clusters are unique, so having one cluster list is perfectly fine (and much cleaner to use), than having multiple cluster lists split up by the multiple lanes. 

Is there any chance this would be possible?

**Comment by Shanomac99** [comment]
After some thinking, this does make the most sense. I’ll add an element within the cluster list stating what lane it belongs to.

**Comment by mahtoid** [comment]
That's not needed, all clusters are prefixed already with their lane.

**Comment by Shanomac99** [comment]
Migrated clusters from within each lane to within main lane object.
