### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by NewGitHubUser0** [Squad-Wiki/squad-wiki-pipeline-map-data#106]
Followed installation steps. Loaded into first Anvil gameplay layer. Pressed "Play" button and got an error.
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/128610313/afedbf55-c5c3-4b67-81c0-797950962001)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/128610313/b54e04da-bfc3-4e02-abbd-f4591661ae98)

**Comment by Shanomac99** [comment]
@NewGitHubUser0 I've gone ahead and pushed a commit in the dev branch with the latest .uasset. Try with that and let me know if your still having issues,

**Comment by NewGitHubUser0** [comment]
@Shanomac99 Hey, THANKS, it works.
