### ISSUE TITLE
INS doesn't have faction name

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#107]
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/583a6928-cee4-474a-9592-37fa216ad8b0)

**Comment by Shanomac99** [comment]
Issue is with short name being used to look up the faction table. The shortname on the faction setup table does not match the faction table for what ever reason 
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/d97dff1a-c66e-4c2f-a535-11adda854280)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/398ea3b8-2cd5-414b-a3ea-63dcb4fbf585)

Changed to use the ID, should fix it.
