### ISSUE TITLE
Cluster name contains spaces in 'Links' 🤔 

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#108]
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/3af9b61d-a38c-47c9-88c8-7ce59ce9095a)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/1593a984-da77-4386-b975-35202fcc07a7)

**Comment by Shanomac99** [comment]
Issue has to do with "objectName" using the actual object name and the LaneLinks (and pointsOrder and listOfMains) utilzing the object's display name. I will be adding an "objectDisplayName" that will be utilized for this. Eventual documentation will note that these use the objects display name.

**Comment by mahtoid** [comment]
@Shanomac99 is there no way to use the display name to capture but extract the actual object name only? I don't see a valid data use case where someone would be wanting to mix-match between the two.

You'd only reference links for the cluster. Seems weird to have to go `objectDisplayName ?? objectName` - but I mean, it still works 🤷

**Comment by Shanomac99** [comment]
I took a closer look. almost everything is using objectDisplayName currently. From the looks of things only the clusters are using objectName. It probably makes more sense to move over utilizing objectDisplayName for them versus changing every else to objectName.
