### ISSUE TITLE
Jensen's default units not added to "Units" object.

### ISSUE THREAD

**Issue by Shanomac99** [Squad-Wiki/squad-wiki-pipeline-map-data#110]
The default units for Jensen's range are not being added to the units object due to them not showing up in the unit list. A special check will need to be added for them to be added to the units object.

**Comment by mahtoid** [comment]
@Shanomac99 still an issue

**Comment by Shanomac99** [comment]
It was an issue with naming, should be fixed. The template names in the map will change.
