### ISSUE TITLE
ERROR_NODISPLAYNAMEINTABLE

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#111]
I think a bugged layer belonging to tutorials causing a bad map?
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/5cf9e3b8-f122-42fb-8c92-46d227390ce6)

**Comment by Shanomac99** [comment]
Looks like it's checked off as not cooked. I'll have top add a manual check for this map, I've tried to find a better solution but can't atm.

**Comment by mahtoid** [comment]
@Shanomac99 broken again on latest
![image](https://github.com/user-attachments/assets/f3921cc7-575b-411d-96ba-6dd7acdb4e95)
