### ISSUE TITLE
Goosebay RAAS V1 Main Protection Zone

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#112]
Team 1 Main Protection zone is wrong

![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/d230820a-9b88-4ce4-b879-3c5fffcb5c66)

**Comment by Shanomac99** [comment]
The issue relates to scaling, for some reason OWI utilized scaling to change the object instead of changing the size of the object. Scaling is now taken into consideration for protection zones.
