### ISSUE TITLE
Manicouagan Seed v1 missing mapTextureCorners

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#113]
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/3aea3a63-b976-43c5-8067-f35bd5ba5dc0)

**Comment by Shanomac99** [comment]
Map utilizes TargetPoints for some reason, added them to the case to look for.
