### ISSUE TITLE
Inconsistent Map sizes

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#114]
Goosebay:
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/7e749961-49cd-4be0-9451-7394272ae3b8)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/436be57b-56ea-4052-acb5-0c8728001391)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/0a425d44-63bb-4e75-a8a5-4f7b97156b0b)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/7a59947d-15b7-49aa-8f20-44fabc3f34b0)

Anvil:
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/362ad019-73e5-47a3-817c-0b3dd716393f)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/d51491b4-10af-4fd6-b307-fd50607e1acc)

Probably others too

**Comment by Eddie0343** [comment]
Checked others, they are correct except for kohat skirmish
![Screenshot 2024-06-16 224251](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/98782419/30a31e61-fd48-4d0e-9136-a0263ddbd760)

**Comment by Shanomac99** [comment]
For goose bay, it appears those maps have different boundaries, meaning that the map size is different.

![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/52398bc1-04c5-4001-945e-239f9830aca7)

![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/3bf7eefc-d276-49c0-80e5-8ae3c1c5019c)

Same thing with Anvil:
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/83b12c1b-e4fb-498f-bb36-55906785a902)

![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/d9e65c8f-faed-4d71-844b-2cbbf251bd07)


Not an issue with the math as it just grabs the farthest points for each map to generate a rough estimate on size, which seems to change here,
