### ISSUE TITLE
Chora Invasion v2 - Broken Cluster Link

### ISSUE THREAD

**Issue by sh4rkman** [Squad-Wiki/squad-wiki-pipeline-map-data#117]
On the last current extracted file, **Chora_Invasion_v2** have links with empty nodes (Link5/6).
Couldn't find any other layers in this case

```json
"clusters": {
    "links": [
      ...
        {
            "name": "Link4",
            "nodeA": "04-CaptureZoneCluster",
            "nodeB": "05-CaptureZoneCluster"
        },
        {
            "name": "Link5",
            "nodeA": "05-CaptureZoneCluster",
            "nodeB": ""
        },
        {
            "name": "Link6",
            "nodeA": "",
            "nodeB": "100-Team2 Main"
        }
    ],
    "pointsOrder": [
        "00-Team1 Main",
        "01-CaptureZoneCluster",
        "02-CaptureZoneCluster",
        "03-CaptureZoneCluster",
        "04-CaptureZoneCluster",
        "05-CaptureZoneCluster",
        "100-Team2 Main"
    ],
```

**Comment by Shanomac99** [comment]
Looks like this is how it is in game. I assume this is messing with something?
![image](https://github.com/user-attachments/assets/5fc82f0e-428f-43c4-bfef-382382d058de)

**Comment by sh4rkman** [comment]
Ah, you are right i should have double check the SDK: thought it was an export problem my bad.

> I assume this is messing with something?

Yeah it is, but OWI's fault ! I'll manually patch it unless more cases like this appear in the futur.
