### ISSUE TITLE
Needs research to see the outlining cause

### ISSUE THREAD

**Issue by werewolfboy13** [Squad-Wiki/squad-wiki-pipeline-map-data#47]
Basrah v4, the layers.json has a lowercase lookup for levelName, when the log parser returns an uppercase version of for the layer in question

**Comment by ect0s** [comment]
`"levelName": "Albasrah_Seed_v1", vs AlBasrah_Seed_v1 
"levelName": "Mestia_Invasion_V2" vs Mestia_Invasion_v2 
"levelName": "Mestia_AAS_V1" vs Mestia_AAS_v1
"levelName": "Albasrah_Invasion_v4" vs AlBasrah_Invasion_V4`

**Comment by werewolfboy13** [comment]
First flag appears to be an issue in the SDK 
![image](https://user-images.githubusercontent.com/43587009/217342979-f7310682-72d1-4531-8834-0ff21155e853.png)

**Comment by werewolfboy13** [comment]
This appears to be an issue with the SDK itself as there is two different versions that I can see.

**Comment by Meeps-13** [comment]
Also, is an issue with `AlBasrah_Invasion_v5`

**Comment by Shanomac99** [comment]
Should be fixed in 82bf155910d62c43b83731e18bf0ffed51ddb667. rawName should have the valid name.
