### ISSUE TITLE
Goes to the next level and not to the next layer

### ISSUE THREAD

**Issue by M3dinar** [Squad-Wiki/squad-wiki-pipeline-map-data#49]
Hello,

I want to use this tool only to generate the JSON file, it will be use by server owner for generating their map rotation and SquadJS.

In the French mod, we use multiple SQ layers for one level, because we got 2 french factions and we want to give the possibility to choose the vanilla opposing faction.
For example Anvil AAS v1:

- FRA10_Anvil_AAS_v1_AUS
- FRA10_Anvil_AAS_v1_CAF
- [...]
- FRA10_Anvil_AAS_v1_USMC
- FRA20_Anvil_AAS_v1_AUS
- [...]
- FRA20_Anvil_AAS_v1_USMC

The loop use the "open level(by name)" node which I don't think allow to open a specific layer.

Any idea, if I can avoid to make my own script it will be great !

**Comment by M3dinar** [comment]
I managed to generate a JSON from the SDK for each level, then fixing some issue in the raw to json converter (it doesn't like vehicle name with a "."). Then pass through a python script in order to generate copy of level entry for each of my need.

**Comment by werewolfboy13** [comment]
@M3dinar sorry are you still needing support regarding this?

**Comment by M3dinar** [comment]
Yep. 
If I can use only the tools and don't make a 3rd party tools in order to get the JSON that I want it will be great.
Moreover I cannot extract the data related to vehicle because I always get the first one so I emptied the vehicle data in my JSON.

**Comment by Shanomac99** [comment]
As for the layer changes, the "open level" node is referencing ue4 levels and not Squad "levels". Was the script having issues loading your modded levels?

**Comment by M3dinar** [comment]
No problem at all.
I modified the asset manager in order to get only the modded map.
I modified the script because I was getting duplicate info due to this issue.
I got 20 layers for the a level, so when the level is loaded it took the first layer data. Due to this issue the next loaded level is the same. I got the same output info instead i should have a different faction. So it's looping 20 times in the same level for nothing.
Intead of incrementing by one the loop, I incremented by 20 in order to get the things done faster.
I tried to look how I could change the layer data between two level but I didn't find a solution. 

I even tried to modify the "override layer" in option from the BP but it does not seem to be took into account.

**Comment by werewolfboy13** [comment]
How does your assets look like. You would need to add a "Map" entry.

**Comment by M3dinar** [comment]
Okay example of our structure.

**data asset for BP_SQLayer:**
FRA10_Anvil_AAS_v2_AUS
FRA10_Anvil_AAS_v2_CAF
FRA10_Anvil_AAS_v2_GB
FRA10_Anvil_AAS_v2_INS
FRA10_Anvil_AAS_v2_MEA
FRA10_Anvil_AAS_v2_MIL
FRA10_Anvil_AAS_v2_PLA
FRA10_Anvil_AAS_v2_RUS
FRA10_Anvil_AAS_v2_USA
FRA10_Anvil_AAS_v2_USMC
FRA20_Anvil_AAS_v2_AUS
FRA20_Anvil_AAS_v2_CAF
FRA20_Anvil_AAS_v2_GB
FRA20_Anvil_AAS_v2_INS
FRA20_Anvil_AAS_v2_MEA
FRA20_Anvil_AAS_v2_MIL
FRA20_Anvil_AAS_v2_PLA
FRA20_Anvil_AAS_v2_RUS
FRA20_Anvil_AAS_v2_USA
FRA20_Anvil_AAS_v2_USMC

Which use the **data table** "LayerTable_Anvil_FRA" with a row structure of SQLayerEntry.

The data asset use the same **level** "Anvil_AAS_v2_FRA"

**Comment by Shanomac99** [comment]
Should be fixed in 82bf155910d62c43b83731e18bf0ffed51ddb667.
