### ISSUE TITLE
New SDK Breaking Changes

### ISSUE THREAD

**Issue by werewolfboy13** [Squad-Wiki/squad-wiki-pipeline-map-data#51]
![image](https://user-images.githubusercontent.com/43587009/226078129-bcc7f624-67ad-4db1-a393-3a5c3e894088.png)
![image](https://user-images.githubusercontent.com/43587009/226078146-757eb02d-91af-4b4b-845c-8c16e7b7b846.png)

@Shanomac99 I will need your assistance fixing these compile errors. 

Notes to team:

Please make seperate branches for each issue getting fixed.

**Comment by Shanomac99** [comment]
Looks like that just affects the helipad logging. Did they change helipads in 4.3?

**Comment by werewolfboy13** [comment]
I will check when I get home.

**Comment by werewolfboy13** [comment]
Asking in the SDK discord. 

Attaching here for the other errors.

![image](https://user-images.githubusercontent.com/43587009/226149058-303cad3d-52a9-48b8-9bf8-ef707a700894.png)

**Comment by Shanomac99** [comment]
I believe it is having issues because the "Get All Actors Of Class" is blank. That should have the helipad blueprint selected.

**Comment by werewolfboy13** [comment]
@Shanomac99 These are the options, which one do I need to select?

![image](https://user-images.githubusercontent.com/43587009/226149283-d19a72dc-9d8d-48c4-aeee-c46d02a3ece6.png)

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/226149309-efceb333-f99b-4336-9a8a-638e288ca3c7.png)

**Comment by Shanomac99** [comment]
@werewolfboy13 It should be a helipad deployable object. Look around one of the maps if it's not in the list there.


My assumption is that they changed the name/path of the deployable and that broke the link.

**Comment by werewolfboy13** [comment]
@Shanomac99 This would be the name correct?

![image](https://user-images.githubusercontent.com/43587009/226149630-c5316913-f731-428c-ab9b-55d0a427d89e.png)

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/226149829-14d8425c-af5c-4beb-a4c4-ed5a370758ba.png)

**Comment by Shanomac99** [comment]
> ![image](https://user-images.githubusercontent.com/43587009/226149829-14d8425c-af5c-4beb-a4c4-ed5a370758ba.png)
> 
> 


Can you send an image of the whole screen? And of the BP you selected under the node

**Comment by werewolfboy13** [comment]
@Shanomac99 its still the same node. 

![image](https://user-images.githubusercontent.com/43587009/226205415-a9b4a49b-91db-4c10-9efb-eaf278c49348.png)

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/226205457-2622651b-1162-4f25-94fc-a82dd622207a.png)

**Comment by Shanomac99** [comment]
> @Shanomac99 its still the same node. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/43587009/226205415-a9b4a49b-91db-4c10-9efb-eaf278c49348.png)
> 
> 

Can you show me an image of what comes up when you search helipad under that node?

I believe there should be two options when it comes up, one a BP, one a class.

If not we might have to rewrite that part.

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/226209997-ca06c660-084b-4f48-9c9e-2edaa2cd602d.png)

**Comment by Shanomac99** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/43587009/226209997-ca06c660-084b-4f48-9c9e-2edaa2cd602d.png)
> 
> 

Okay, last thing. Try deleting the For loop and recreating it off the get all actors array.

**Comment by werewolfboy13** [comment]
@Shanomac99 not allowed.

**Comment by werewolfboy13** [comment]
Compile errors fixed. Running Soft Tests.
