### ISSUE TITLE
Naming inconsistent in JSON and images 

### ISSUE THREAD

**Issue by AZalshehri7** [Squad-Wiki/squad-wiki-pipeline-map-data#57]
The naming of some layers are not consistent between images and JSON in current version.

Here is an example:
JSON:
`Yehorivka_TC_v2`
Image: (Capital V)
`Yehorivka_TC_V2`

**Comment by werewolfboy13** [comment]
@AZalshehri7 Where are you seeing these? This may be a similar issue with #47

**Comment by werewolfboy13** [comment]
No response, closing.
