### ISSUE TITLE
Cluster names and link names do not always match

### ISSUE THREAD

**Issue by Shanomac99** [Squad-Wiki/squad-wiki-pipeline-map-data#77]
Narva RAAS v6 for example:

![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/11017547/6e8d1f1d-6cd2-405a-9182-98fd91df30bc)

**Comment by mahtoid** [comment]
Also, may be worth adding a mains obj with the team1 main and team2 main - since Squad loves to use different names for mains Team1Main_0 && Team1Main (idk what else).

**Comment by Shanomac99** [comment]
Fixed and added a new mains object
