### ISSUE TITLE
Chora Insurgency v1 incorrect main coords

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#79]
Every other layer is correct

![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/18308c63-4626-47a2-bf52-de36b8a25939)

**Comment by Shanomac99** [comment]
Team 1 main lines up.

Team 2 main does not line up with data in SDK. Verified data present in JSON is the same as in SDK. Unsure if issue is with the data or with Squad Maps.

**Comment by mahtoid** [comment]
@Shanomac99 So there was a slight issue with SquadMaps which I have fixed and pushed to our `dev` branch. However, there still seems to be an issue. Quite a lot of incorrect mains or missing mains captured from pipeline.

Chora and Fallujah seem to be correct, but the rest seem to have issues. Screenshots below are SquadMaps v2 vs SquadMaps v1 (which could be slightly outdated). 

### Al Basrah (multi mains, missing spawn)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/cb20efee-e359-4855-843c-2b54400b2adb)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/75da2ae8-41fc-4b27-a529-8e5ef2ef8e5c)

### Gorodok (missing spawns)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/06c2b606-346a-4f62-ab84-0d02a3af6995)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/b9996d57-a964-4bef-973b-5fa5ba3d7185)


### Kokan (double main)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/08bbdfaf-2015-4b08-b577-223d61b4db8f)
![image](https://github.com/Squad-Wiki/squad-wiki-pipeline-map-data/assets/56257224/e7af3696-3056-469d-a638-3af644604bca)

The other maps contain issues too, but those two repeat. I wonder if it is a one or two solve, solves all.

**Comment by Shanomac99** [comment]
@mahtoid  Minus the multiple points none of the positions are incorrect right? They all look correct to me. 

I have a suspicion that i’m logging something incorrectly with insurgency main points. I’ve also noticed there are a few blank elements in the JSON for Chora, might be related.

I also need to think about “resupply” points. I’ll take a look to see what they consist of and see if we can separate them from mains.

**Comment by mahtoid** [comment]
@Shanomac99 I'd say they are either missing or multiple - not incorrect, sure.

**Comment by Shanomac99** [comment]
@mahtoid  Perfect, just making sure there aren’t any like halfway across the map when they are supposed to be in a corner.

**Comment by Shanomac99** [comment]
@mahtoid Does Squad Maps utilize the boxes for detecting where to put mains? Or just the location within the objective object?

The objects in the capture points are the points where the point is "capturable", or for mains where vehicles can grab supplies.

That could be why there are multiple mains.

**Comment by Shanomac99** [comment]
@mahtoid As for the missing "points" it looks like those are temporary spawn points which are not currently logged. Looks like there is also a "maxNum" of vehicles for the vehicle spawners. I'm going to create new issues for these two, as they aren't neccessarly a bug.

**Comment by mahtoid** [comment]
> Does Squad Maps utilize the objects object for detecting where to put mains? Or just the location within the objective object?
`capturePoints.objectives[_Main_].objects`

**Comment by Shanomac99** [comment]
> `capturePoints.objectives[_Main_].objects`

You should be using the cords found in the _Main_ objectives themselves, not the inner objects. Like I said above those boxes/spheres are used for determining where people can rearm vehicles.

**Comment by mahtoid** [comment]
Ah yeah, true. Once the temporary spawns is captured as well (in your other issue), then this is grand.

**Comment by Shanomac99** [comment]
Other two issues were solved, closing this.
