### ISSUE TITLE
Clusters as Objects instead of Object Arrays 👀 

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#87]
I don't know who suggested this, but it was really stupid (tl'dr for on-lookers, it was me originally). 

It would be great if Clusters and wherever else I suggested - to be using Objects instead of Object Arrays. I am an actual ape. 

For example, my YAML -> JSON of SquadLanes data:
```
"Clusters": {
        "02-CaptureZoneCluster": [
          {
            "display_name": "Al Khora",
            "sdk_name": "AlKhora_808",
            "x": -84917.90625,
            "y": 34536.859375
          }
        ],
        "03-CaptureZoneCluster": [
          {
            "display_name": "Poppy Production",
            "sdk_name": "PoppyProduction",
            "x": -54764.84375,
            "y": 35760.15625
          },
          {
            "display_name": "Warlord's Compound",
            "sdk_name": "WarlordsCompound",
            "x": -38742.09765625,
            "y": 46751.796875
          }
        ],
```

---

If you want to punish me, give me the down low on where this is set up, and I will change it for suggesting this stupidly in the first place. Sorry! 💜

**Comment by Shanomac99** [comment]
Converted `clusters` in both cluster based RAAS and lane based RAAS.
