### ISSUE TITLE
Team Main mislabeled in Clusters.

### ISSUE THREAD

**Issue by mahtoid** [Squad-Wiki/squad-wiki-pipeline-map-data#99]
The Main cluster should be using the objectName, for example `00-Team1Main` or `Z-Team2Main` (whatevever the respective main names are for the layer). However, they (Team 2, currently bug under Team 1) is labelled under `Main`.

**Comment by Shanomac99** [comment]
Changed script to pull `objectName` instead of `name` for main objectives. Will represent 00-Team1Main or Z-Team2Main and the list found in `listOfMains`.

**Comment by Shanomac99** [comment]
Need to process extraction first before closing.
